Add sticky_video component and stick and close actions
guardian/libs pull request #315
Opened 2022-03-02 17:28 UTC by marjisound

## What does this change?
This PR adds a new component STICKY_VIDEO and also adds two actions STICK & CLOSE 
## Why?
In order to track when a sticky video sticks to screen and when the sticky video is closed

Another PR is created in ophan to add these to the thrift https://github.com/guardian/ophan/pull/4440

2022-03-02 23:29 UTC, sndrs requested changes
is this actually fixing something that was broken? it looks more like new functionality being added, which would be a new `feat` (if correct)

also, it's really helpful to explain in the PR title what's being affected. i assumed you were adding a sticky video component to libs, which def seemed the wrong place! but on closer inspection it's adding a new field that can be reported to ophan. the more information context a PR can provide the easier it is for reviewers to understand what the author is intending

2022-03-02 23:35 UTC, sndrs commented
not for this PR, but would it be easier to publish ophan types from ophan's codebase itself? the concomitant PR to ophan's thrift types will always need to be accompanied by one here i think? is it useful to separate them?

2022-03-03 09:04 UTC, marjisound commented
> not for this PR, but would it be easier to publish ophan types from ophan's codebase itself? the concomitant PR to ophan's thrift types will always need to be accompanied by one here i think? is it useful to separate them?

Thanks @sndrs for pointing it out. Do you think I should talk to Roberto about this?

2022-03-03 09:06 UTC, marjisound commented
> is this actually fixing something that was broken? it looks more like new functionality being added, which would be a new `feat` (if correct)
> 
> also, it's really helpful to explain in the PR title what's being affected. i assumed you were adding a sticky video component to libs, which def seemed the wrong place! but on closer inspection it's adding a new field that can be reported to ophan. the more information context a PR can provide the easier it is for reviewers to understand what the author is intending

Thanks @sndrs I changed the commit and PR message, do you think it's more descriptive of what it's doing now?

2022-03-03 10:35 UTC, merged